##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Oct 25 11:20:39 2013 guillaume marescaux
## Last update Tue Oct 29 15:14:14 2013 alexis mestag
##

CIRCULAR_BUFFER_PATH=	$(SRC_PATH)/CircularBuffer
SERVER_PATH=		$(SRC_PATH)/Server
ENTITIES_PATH=		$(SRC_PATH)/Entities

SRC=			$(SRC_PATH)/main.cpp

include			$(CIRCULAR_BUFFER_PATH)/Makefile
include			$(SERVER_PATH)/Makefile
include			$(ENTITIES_PATH)/Makefile
