##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Oct 25 11:20:39 2013 guillaume marescaux
## Last update Fri Oct 25 15:22:22 2013 guillaume marescaux
##

CIRCULAR_BUFFER_PATH=	$(SRC_PATH)/CircularBuffer
SERVER_PATH=		$(SRC_PATH)/Server

SRC=			$(SRC_PATH)/main.cpp

include			$(CIRCULAR_BUFFER_PATH)/Makefile
include			$(SERVER_PATH)/Makefile

