##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Mon Nov  4 23:15:27 2013 antoine maitre
##

WEAPON=		$(ENTITIES)/Weapon

SRCGAMELOOP +=	$(ENTITIES)/AEntity.cpp \
		$(ENTITIES)/Coordinate.cpp \
		$(ENTITIES)/Mob.cpp \

include		$(WEAPON)/Makefile
