##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Wed Nov  6 14:38:27 2013 antoine maitre
##

WEAPON=		$(ENTITIES)/Weapon

SRCSERVER +=	$(ENTITIES)/AEntity.cpp \
		$(ENTITIES)/Coordinate.cpp \
		$(ENTITIES)/Mob.cpp \
		$(ENTITIES)/ACharacter.cpp \
		$(ENTITIES)/Player.cpp \

include		$(WEAPON)/Makefile
