##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Oct 25 15:20:37 2013 guillaume marescaux
## Last update Fri Oct 25 15:22:31 2013 guillaume marescaux
##

SRC +=		$(SERVER_PATH)/Select.cpp

