##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:54:38 2013 laurent ansel
## Last update Tue Oct 29 16:23:35 2013 laurent ansel
##

SRCCOMMON +=			$(HEADER)/Header.cpp
