##
## Makefile<3> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 15:43:44 2013 laurent ansel
## Last update Tue Oct 29 16:11:23 2013 laurent ansel
##

SRCSERVER +=	$(SOURCESERVER)/Server.cpp
