##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Sun Nov 17 16:13:20 2013 guillaume marescaux
## Last update Sun Nov 17 16:13:58 2013 guillaume marescaux
##

SRCCOMMON +=	$(MD5)/md5.cpp
