##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:57:56 2013 laurent ansel
## Last update Tue Oct 29 16:23:20 2013 laurent ansel
##

SRCCOMMON +=			$(CIRCULAR_BUFFER_MANAGER)/CircularBufferManager.cpp

CIRCULAR_BUFFER=		$(CIRCULAR_BUFFER_MANAGER)/CircularBuffer

include				$(CIRCULAR_BUFFER)/Makefile
