##
## Makefile<6> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:21:24 2013 laurent ansel
## Last update Mon Oct 28 16:22:08 2013 laurent ansel
##

SRCSERVER +=		$(THREAD)/UnixThread.cpp		\
			$(THREAD)/PthreadCondition.cpp		\
			$(THREAD)/WindowsThread.cpp
