##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 14:48:04 2013 guillaume marescaux
## Last update Mon Nov  4 23:15:38 2013 antoine maitre
##

SRCGAMELOOP +=	$(WEAPON)/Weapon.cpp \
		$(WEAPON)/AProjectile.cpp \
		$(WEAPON)/Rocket.cpp \
