##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Oct 25 11:22:05 2013 guillaume marescaux
## Last update Fri Oct 25 12:53:41 2013 guillaume marescaux
##

SRC +=		$(CIRCULAR_BUFFER_PATH)/CircularBufferManager.cpp \
		$(CIRCULAR_BUFFER_PATH)/CircularBuffer.cpp \
