##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:20:35 2013 laurent ansel
## Last update Mon Oct 28 16:21:15 2013 laurent ansel
##

SRCSERVER +=		$(SOCKET)/UnixSocketClient.cpp		\
			$(SOCKET)/WindowsSocketClient.cpp	\
			$(SOCKET)/UnixSocket.cpp		\
			$(SOCKET)/WindowsSocket.cpp
