##
## Makefile<3> for  in /home/jourda_c/Documents/C++/Rtype_GIT/rtype/rtype/Client/src/Graphic/Graphics
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Sun Nov 17 22:21:28 2013 cyril jourdain
## Last update Sun Nov 17 22:30:35 2013 cyril jourdain
##

SRCCLIENT += 	$(SPRITES)/ASprite.cpp \
		$(SPRITES)/FixedSprite.cpp	
