##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Tue Oct 29 19:07:39 2013 antoine maitre
##

SRC +=		$(LEVEL_PATH)/LevelManager.cpp \
		$(LEVEL_PATH)/Level.cpp	\
		$(LEVEL_PATH)/Map.cpp

