##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:20:35 2013 laurent ansel
## Last update Tue Oct 29 16:24:11 2013 laurent ansel
##

SRCCOMMON +=		$(SOCKET)/UnixSocketClient.cpp		\
			$(SOCKET)/WindowsSocketClient.cpp	\
			$(SOCKET)/UnixSocket.cpp		\
			$(SOCKET)/WindowsSocket.cpp
