##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 14:48:04 2013 guillaume marescaux
## Last update Mon Oct 28 14:48:41 2013 guillaume marescaux
##

SRC +=		$(WEAPON_PATH)/Weapon.cpp \
		$(WEAPON_PATH)/AProjectile.cpp \
		$(WEAPON_PATH)/Rocket.cpp \
