##
## Makefile<2> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sun Nov 10 15:46:19 2013 laurent ansel
## Last update Sun Nov 10 15:48:00 2013 laurent ansel
##

SRCSERVER +=	$(SPRITELOADER)/SpriteLoader.cpp	\
		$(SPRITELOADER)/SpriteLoaderManager.cpp	\
		$(SPRITELOADER)/SpriteLoaderUpdater.cpp
