##
## Makefile for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 16:03:16 2013 laurent ansel
## Last update Tue Oct 29 16:11:41 2013 laurent ansel
##

SRCSERVER +=	$(COMMAND)/Command.cpp
