##
## Makefile for  in /home/ansel_l/Documents/Rtype/work/Server/include/ObjectPoolManager
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Wed Nov  6 17:46:53 2013 laurent ansel
## Last update Wed Nov  6 18:37:37 2013 laurent ansel
##

SRCSERVER +=	$(OBJECTPOOL)/ObjectPoolManager.cpp	\
		$(OBJECTPOOL)/ObjectPoolUpdater.cpp
