##
## Makefile<2> for Rtype in /home/mestag_a/Documents/Projets/Tek3/RType/rtype/rtype/Server/src
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Sat Nov  2 18:00:02 2013 alexis mestag
## Last update Mon Nov  4 10:20:41 2013 laurent ansel
##

SRCSERVER +=	$(DYNAMICLIBRARY)/UnixDynamicLibrary.cpp	\
		$(DYNAMICLIBRARY)/WindowsDynamicLibrary.cpp	\
		$(DYNAMICLIBRARY)/DynamicLibrary.cpp

ifndef _WIN32
LDFLAGS +=	-ldl
endif
