##
## Makefile for RType in /home/mestag_a/Documents/Projets/Tek3/RType/Server/src/FileSystem
## 
## Made by alexis mestag
## Login   <mestag_a@epitech.net>
## 
## Started on  Mon Nov  4 14:25:38 2013 alexis mestag
## Last update Tue Nov 12 13:55:29 2013 guillaume marescaux
##

SRCCOMMON +=	$(FILESYSTEM)/Entry.cpp		\
		$(FILESYSTEM)/File.cpp		\
		$(FILESYSTEM)/Directory.cpp
