##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sat Nov  2 18:08:57 2013 laurent ansel
## Last update Tue Nov 19 20:37:43 2013 alexis mestag
##

SRCCOMMON +=	$(ACTION)/Action.cpp

AIDEP	+= $(ACTION)/Action.cpp
