##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sat Nov  2 18:08:57 2013 laurent ansel
## Last update Mon Nov 18 16:57:56 2013 cyril jourdain
##

SRCCOMMON +=	$(ACTION)/Action.cpp
