##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sat Nov  2 18:08:57 2013 laurent ansel
## Last update Sat Nov 23 22:12:26 2013 alexis mestag
##

SRCAI +=	$(AI)/Donkey.cpp	\
		$(AI)/Snake.cpp
AIDIR =		$(AI)
