##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sat Nov  2 18:08:57 2013 laurent ansel
## Last update Tue Nov 19 11:15:27 2013 alexis mestag
##

# NEEDEDAI +=		$(ACTION)/Action.cpp		\
# 			$(ENTITIES)/AEntity.cpp		\
# 			$(ENTITIES)/ACharacter.cpp	\
# 			$(ENTITIES)/Mob.cpp

SRCAI +=	$(AI)/Donkey.cpp
AIDIR =		$(AI)
