##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Fri Oct 25 11:20:39 2013 guillaume marescaux
## Last update Mon Nov  4 17:22:41 2013 guillaume marescaux
##

SRCCLIENT=		$(CLIENT_SRC)/main.cpp

GAME=			$(CLIENT_SRC)/Game
CORE=			$(CLIENT_SRC)/Core
MAP=			$(CLIENT_SRC)/Map

include			$(GAME)/Makefile
include			$(CORE)/Makefile
include			$(MAP)/Makefile
