##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 14:48:04 2013 guillaume marescaux
## Last update Tue Nov  5 10:13:33 2013 laurent ansel
##

SRCSERVER +=	$(WEAPON)/Weapon.cpp \
		$(WEAPON)/AProjectile.cpp \
		$(WEAPON)/Rocket.cpp \
