##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 14:48:04 2013 guillaume marescaux
## Last update Tue Nov 19 17:54:21 2013 alexis mestag
##

SRCSERVER +=	$(WEAPON)/Weapon.cpp \
		$(WEAPON)/AProjectile.cpp \
		$(WEAPON)/Rocket.cpp \

AIDEP	+=	$(WEAPON)/Weapon.cpp \
		$(WEAPON)/AProjectile.cpp
