##
## Makefile for  in /home/ansel_l/Documents/Rtype/rtype/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:05:51 2013 laurent ansel
## Last update Tue Oct 29 14:40:42 2013 laurent ansel
##

SRCSERVER +=	$(SERVER_SRC)/main.cpp	\
		$(SERVER_SRC)/Server.cpp

SERVER_INCLUDES=	-I $(SERVER)/include
