##
## Makefile<4> for  in /home/jourda_c/Documents/C++/RType/Sources/include
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Wed Nov  6 13:52:16 2013 cyril jourdain
## Last update Wed Nov  6 13:56:05 2013 cyril jourdain
##

SRCCLIENT += 	$(SFGRAPHICS)/SFTextBox.cpp \
		$(SFGRAPHICS)/WindowManager.cpp \
		$(SFGRAPHICS)/SFWidget.cpp \
		$(SFGRAPHICS)/SFButton.cpp \
		$(SFGRAPHICS)/SFImageLoader.cpp \
		$(SFGRAPHICS)/SFImageBox.cpp \
		$(SFGRAPHICS)/SFRessourcesManager.cpp \
		$(SFGRAPHICS)/SFFontLoader.cpp \
		$(SFGRAPHICS)/SFLabel.cpp \
		$(SFGRAPHICS)/SFWindow.cpp \
