##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Nov  4 17:21:55 2013 guillaume marescaux
## Last update Mon Nov  4 17:23:33 2013 guillaume marescaux
##

SRCCLIENT +=		$(MAP)/Map.cpp \
			$(MAP)/Entity.cpp
