##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:56:24 2013 laurent ansel
## Last update Tue Oct 29 16:23:26 2013 laurent ansel
##

SRCCOMMON +=			$(CIRCULAR_BUFFER)/CircularBuffer.cpp

TRAME=				$(CIRCULAR_BUFFER)/Trame

include				$(TRAME)/Makefile
