##
## Makefile<2> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Sun Nov 10 00:04:29 2013 laurent ansel
## Last update Sun Nov 10 00:04:56 2013 laurent ansel
##

SRCSERVER +=	$(INOTIFY)/UnixInotify.cpp
