##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Tue Oct 29 14:45:47 2013 guillaume marescaux
## Last update Tue Oct 29 16:12:41 2013 guillaume marescaux
##

SRCCLIENT +=		$(GAME)/GameInfo.cpp \
			$(GAME)/GameList.cpp
