##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Tue Oct 29 16:24:02 2013 laurent ansel
##

SRCCOMMON +=			$(MUTEX)/UnixMutex.cpp		\
				$(MUTEX)/WindowsMutex.cpp
