##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Tue Nov 19 20:56:51 2013 alexis mestag
##

SRCCOMMON +=			$(MUTEX)/UnixMutex.cpp		\
				$(MUTEX)/WindowsMutex.cpp

AIDEP +=			$(MUTEX)/UnixMutex.cpp
# $(subst src/, include/, $(MUTEX)/Mutex.hpp		\
# $(MUTEX)/MutexVar.hpp	)
