##
## Makefile<3> for  in /home/jourda_c/Documents/C++/RType/Sources/include
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Wed Nov  6 13:49:37 2013 cyril jourdain
## Last update Sun Nov 17 22:21:22 2013 cyril jourdain
##

SPRITES=	$(GRAPHICS)/Sprites

include	$(SPRITES)/Makefile

SRCCLIENT +=	$(GRAPHICS)/LobbyWindow.cpp \
		$(GRAPHICS)/LoginWindow.cpp \
		$(GRAPHICS)/GameWindow.cpp \
		$(GRAPHICS)/GameView.cpp
