##
## Makefile<3> for  in /home/jourda_c/Documents/C++/RType/Sources/include
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Wed Nov  6 13:49:37 2013 cyril jourdain
## Last update Sat Nov 16 18:40:33 2013 cyril jourdain
##

SRCCLIENT +=	$(GRAPHICS)/LobbyWindow.cpp \
		$(GRAPHICS)/LoginWindow.cpp \
		$(GRAPHICS)/GameWindow.cpp \
		$(GRAPHICS)/GameView.cpp \
