##
## Makefile<4> for  in /home/ansel_l/Documents/Rtype/rtype
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:19:26 2013 laurent ansel
## Last update Mon Oct 28 21:30:18 2013 laurent ansel
##

SRCSERVER +=			$(MUTEX)/UnixMutex.cpp		\
				$(MUTEX)/WindowsMutex.cpp
