##
## Makefile<3> for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 12:55:20 2013 laurent ansel
## Last update Tue Oct 29 16:23:31 2013 laurent ansel
##

SRCCOMMON +=			$(TRAME)/Trame.cpp

HEADER=				$(TRAME)/Header

include				$(HEADER)/Makefile
