##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Mon Oct 28 14:47:54 2013 guillaume marescaux
##

WEAPON_PATH=	$(ENTITIES_PATH)/Weapon

SRC +=		$(ENTITIES_PATH)/AEntity.cpp \
		$(ENTITIES_PATH)/Coordinate.cpp \

include		$(WEAPON_PATH)/Makefile
