##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Tue Nov  5 12:45:24 2013 laurent ansel
##

SRCSERVER +=	$(GAMELOOP)/GameLoop.cpp \
		$(GAMELOOP)/GameLoopManager.cpp \
		$(GAMELOOP)/PlayerInfo.cpp
