##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 16:06:09 2013 laurent ansel
## Last update Mon Nov 18 13:38:17 2013 alexis mestag
##

CLIENTINFO=		$(SERVER_SRC)/ClientInfo
COMMAND=		$(SERVER_SRC)/Command
SOURCESERVER=		$(SERVER_SRC)/Server
ACTION=			$(SERVER_SRC)/Action
DYNAMICLIBRARY=		$(SERVER_SRC)/DynamicLibrary
GAMELOOP=		$(SERVER_SRC)/GameLoop
LEVEL=			$(SERVER_SRC)/Level
ENTITIES=		$(SERVER_SRC)/Entities
OBJECTPOOL=		$(SERVER_SRC)/ObjectPoolManager
INOTIFY=		$(SERVER_SRC)/Inotify
SPRITELOADER=		$(SERVER_SRC)/SpriteLoaderManager
AI=			$(SERVER_SRC)/AI

include			$(CLIENTINFO)/Makefile
include			$(COMMAND)/Makefile
include			$(SOURCESERVER)/Makefile
include			$(ACTION)/Makefile
include			$(DYNAMICLIBRARY)/Makefile
include			$(GAMELOOP)/Makefile
include			$(LEVEL)/Makefile
include			$(ENTITIES)/Makefile
include			$(OBJECTPOOL)/Makefile
include			$(INOTIFY)/Makefile
include			$(SPRITELOADER)/Makefile
include			$(AI)/Makefile
