##
## Makefile<5> for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 16:06:09 2013 laurent ansel
## Last update Mon Nov  4 17:48:01 2013 alexis mestag
##

CLIENTINFO=		$(SERVER_SRC)/ClientInfo
COMMAND=		$(SERVER_SRC)/Command
SOURCESERVER=		$(SERVER_SRC)/Server
ACTION=			$(SERVER_SRC)/Action
DYNAMICLIBRARY=		$(SERVER_SRC)/DynamicLibrary
FILESYSTEM=		$(SERVER_SRC)/FileSystem

include			$(CLIENTINFO)/Makefile
include			$(COMMAND)/Makefile
include			$(SOURCESERVER)/Makefile
include			$(ACTION)/Makefile
include			$(DYNAMICLIBRARY)/Makefile
include			$(FILESYSTEM)/Makefile
