##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Tue Oct 29 16:27:35 2013 guillaume marescaux
## Last update Wed Nov  6 17:37:02 2013 guillaume marescaux
##

SRCCLIENT +=		$(CORE)/Client.cpp \
			$(CORE)/Protocol.cpp  \
			$(CORE)/ConnectInfo.cpp
