##
## Makefile for  in /home/jourda_c/Documents/C++/Rtype_test/rtype/rtype
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Sat Nov 23 20:14:53 2013 cyril jourdain
## Last update Sat Nov 23 20:20:22 2013 cyril jourdain
##

SRCCLIENT +=	$(SOUND)/SoundManager.cpp
