##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Tue Nov  5 10:13:15 2013 laurent ansel
##

SRCSERVER +=		$(LEVEL)/LevelManager.cpp \
			$(LEVEL)/Level.cpp	\
			$(LEVEL)/Map.cpp

