##
## Makefile for  in /home/jourda_c/Documents/C++/RType/Sources/src
## 
## Made by cyril jourdain
## Login   <jourda_c@epitech.net>
## 
## Started on  Wed Nov  6 13:37:58 2013 cyril jourdain
## Last update Sat Nov 23 20:16:24 2013 cyril jourdain
##

GRAPHICS=	$(GRAPHIC)/Graphics
SFGRAPHICS=	$(GRAPHIC)/SFGraphics

include		$(GRAPHICS)/Makefile
include		$(SFGRAPHICS)/Makefile

SRCCLIENT +=	$(GRAPHIC)/ClientMain.cpp

LDFLAGS+=	-lsfml-system -lsfml-window -lsfml-graphics -lsfml-audio
