##
## Makefile for  in /home/ansel_l/Documents/Rtype/work/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Tue Oct 29 15:42:36 2013 laurent ansel
## Last update Sat Nov  2 18:09:03 2013 laurent ansel
##

SRCSERVER +=	$(CLIENTINFO)/ClientInfo.cpp
