##
## Makefile for  in /home/ansel_l/Documents/Rtype/rtype/Server
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 16:05:51 2013 laurent ansel
## Last update Mon Nov  4 23:13:29 2013 antoine maitre
##

LEVEL=			$(GAMELOOP_SRC)/Level
GAME=			$(GAMELOOP_SRC)/Game
ENTITIES=		$(GAMELOOP_SRC)/Entities

include			$(LEVEL)/Makefile
include			$(GAME)/Makefile
include			$(ENTITIES)/Makefile

GAMELOOP_INCLUDES=		-I $(GAMELOOP)/include
