##
## Makefile<2> for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Tue Oct 29 13:27:44 2013 guillaume marescaux
## Last update Tue Oct 29 15:58:38 2013 guillaume marescaux
##

CLIENT_INCLUDES=	-I $(CLIENT)/include

include			$(CLIENT_SRC)/Makefile
