##
## Makefile for  in /home/ansel_l/Documents/Rtype/work
## 
## Made by laurent ansel
## Login   <ansel_l@epitech.net>
## 
## Started on  Mon Oct 28 21:29:54 2013 laurent ansel
## Last update Tue Oct 29 12:54:53 2013 laurent ansel
##

SRCSERVER +=			$(SELECT)/Select.cpp
