##
## Makefile for  in /home/maresc_g/Projets/en_cours/rtypeSource
## 
## Made by guillaume marescaux
## Login   <maresc_g@epitech.net>
## 
## Started on  Mon Oct 28 13:56:38 2013 guillaume marescaux
## Last update Mon Nov  4 23:17:00 2013 antoine maitre
##

SRCGAMELOOP +=		$(LEVEL)/LevelManager.cpp \
			$(LEVEL)/Level.cpp	\
			$(LEVEL)/Map.cpp

